# Generated by Django 2.0.7 on 2018-07-03 22:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LidarFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('srs', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('web_srs', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('epsg', models.IntegerField(blank=True, null=True)),
                ('point_count', models.IntegerField(blank=True, null=True)),
                ('las_file', models.FileField(null=True, upload_to='las/')),
                ('file_size', models.FloatField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('scale', models.CharField(blank=True, max_length=500, null=True)),
                ('offset', models.CharField(blank=True, max_length=500, null=True)),
                ('min_max_XYZ', models.CharField(blank=True, max_length=500, null=True)),
                ('sys_id', models.CharField(blank=True, max_length=250, null=True)),
                ('software_id', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LidarStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('height_raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('pulse_count_raster', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('returns', models.IntegerField(blank=True, null=True)),
                ('z_range', models.FloatField(blank=True, null=True)),
                ('mean_z', models.FloatField(blank=True, null=True)),
                ('std_dev', models.FloatField(blank=True, null=True)),
                ('x_range', models.FloatField(blank=True, null=True)),
                ('y_range', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
